#!/bin/bash
python validate_xml_with_schema.py aggregatereport.xsd aggregatereport.xml
python validate_xml_with_schema.py allergy.xsd allergy.xml
python validate_xml_with_schema.py annotation.xsd annotation.xml
python validate_xml_with_schema.py contact.xsd contact.xml
python validate_xml_with_schema.py demographics.xsd demographics.xml
python validate_xml_with_schema.py device.xsd device.xml
python validate_xml_with_schema.py equipment.xsd equipment.xml
python validate_xml_with_schema.py healthactionoccurrence.xsd healthactionoccurrence.xml
python validate_xml_with_schema.py healthactionplan.xsd healthactionplan.xml
python validate_xml_with_schema.py healthactionresult.xsd healthactionresult.xml
python validate_xml_with_schema.py healthactionschedule.xsd healthactionschedule.xml
python validate_xml_with_schema.py hospital-api-metadata.xsd hospital-api-metadata.xml
python validate_xml_with_schema.py immunization.xsd immunization.xml
python validate_xml_with_schema.py lab.xsd lab.xml
python validate_xml_with_schema.py labreport.xsd labreport.xml
python validate_xml_with_schema.py healthmeasurement.xsd healthmeasurement.xml
python validate_xml_with_schema.py medication.xsd medication.xml
python validate_xml_with_schema.py medicationschedule.xsd medicationschedule.xml
python validate_xml_with_schema.py metadata.xsd metadata.xml
python validate_xml_with_schema.py problem.xsd problem.xml
python validate_xml_with_schema.py procedure.xsd procedure.xml
python validate_xml_with_schema.py reporting.xsd reporting.xml
python validate_xml_with_schema.py simplenote.xsd simplenote.xml
python validate_xml_with_schema.py vitals.xsd vitals.xml
