from django.conf.urls.defaults import *

from indivo.views import *
from indivo.lib.utils import MethodDispatcher

urlpatterns = patterns('',
  (r'^minimal/measurements/(?P<lab_code>[^/]+)/$', 
   MethodDispatcher({'GET':measurement_list})),
  (r'^minimal/immunizations/$', 
   MethodDispatcher({'GET':immunization_list})),
  (r'^minimal/allergies/$', 
   MethodDispatcher({'GET':allergy_list})),
  (r'^minimal/labs/$', 
   MethodDispatcher({'GET':lab_list})),
  (r'^minimal/medications/$', 
   MethodDispatcher({'GET':medication_list})),
  (r'^minimal/medicationorders/$',
   MethodDispatcher({'GET':medicationorder_list})),
  (r'^minimal/medicationfills/$',
   MethodDispatcher({'GET':medicationfill_list})),
  (r'^minimal/medicationadministrations/$',
   MethodDispatcher({'GET':medicationadministration_list})),
  (r'^minimal/medicationscheduleitems/$',
   MethodDispatcher({'GET':medicationscheduleitem_list})),
  (r'^minimal/equipmentscheduleitems/$',
   MethodDispatcher({'GET':equipmentscheduleitem_list})),
  (r'^minimal/adherenceitems/$',
   MethodDispatcher({'GET':adherenceitem_list})),
  (r'^minimal/videomessages/$',
   MethodDispatcher({'GET':videomessage_list})),
  (r'^minimal/devices/$',
   MethodDispatcher({'GET':device_list})),
  (r'^minimal/healthmeasurements/$',
   MethodDispatcher({'GET':healthmeasurement_list})),
  (r'^minimal/medicationschedules/$',
   MethodDispatcher({'GET':medicationschedule_list})),
  (r'^minimal/healthactionoccurrences/$',
   MethodDispatcher({'GET':healthactionoccurrence_list})),
  (r'^minimal/healthactionschedules/$',
   MethodDispatcher({'GET':healthactionschedule_list})),
  (r'^minimal/healthactionplans/$',
   MethodDispatcher({'GET':healthactionplan_list})),
  (r'^minimal/healthactionresults/$',
   MethodDispatcher({'GET':healthactionresult_list})),
  (r'^minimal/procedures/$', 
   MethodDispatcher({'GET':procedure_list})),
  (r'^minimal/problems/$', 
   MethodDispatcher({'GET':problem_list})),
  (r'^minimal/equipment/$', 
   MethodDispatcher({'GET':equipment_list})),
  (r'^minimal/simple-clinical-notes/$', 
   MethodDispatcher({'GET':simple_clinical_notes_list})),
  (r'^minimal/vitals/$', 
   MethodDispatcher({'GET':vitals_list})),
  (r'^minimal/vitals/(?P<category>[^/]+)/$', 
   MethodDispatcher({'GET':vitals_list})),
  (r'^experimental/ccr$', 
   MethodDispatcher({'GET':report_ccr})),
)
